language: python

install:
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -y libnss-db libdb-dev libcurl4-gnutls-dev python3-mox3 python3-bsddb3 python-pycurl
 - pip install .
 - travis_retry pip install -r requirements.txt

script:
 - bash tests/samba.sh
 - python runtests.py
 - python setup.py install --root=/tmp/nsscache

python:
 - "3.7"
 - "3.8"
 - "nightly"
matrix:
 fast_finish: true
 allow_failures:
  - python: nightly
