language: python

install:
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -y libnss-db python-ldap python-mox python-pycurl
 - pip install .
 - travis_retry pip install -r requirements.txt

script:
 - ./runtests.py
 - python setup.py install --root=/tmp/nsscache

python:
 - "3.8"
 - "nightly"
matrix:
 fast_finish: true
 allow_failures:
  - python: nightly
