language: python

install:
 - travis_retry sudo apt-get update -qq
 - travis_retry sudo apt-get install -y python-ldap python-mox libnss-db python-boto3

script:
 - ./runtests.py
 - python setup.py install --root=/tmp/nsscache

python:
 - "2.6"
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
 - "3.5"
 - "3.5-dev" # 3.5 development branch
 - "nightly" # currently points to 3.6-dev
matrix:
 fast_finish: true
 allow_failures:
  - python: nightly
  - python: 3.5-dev
  - python: 3.5
  - python: 3.4
  - python: 3.3
  - python: 3.2

