version: 2

jobs:
  build:
    working_directory: ~/nsscache
    machine:
      image: ubuntu-1604:201903-01
    envireonment:
      PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      #- run:
      #    name: Make PATH available globally
      #    command: |
      #      echo 'export PATH=$PATH:/home/circleci/.local/bin' >> $BASH_ENV
      #      #source $BASH_ENV
      #      #source /home/circleci/.bashrc
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0
      # Install C libraries before pip install.
      - run: which python
      - run: which python3
      #- run: sudo apt-get -qq update
      #- run: sudo apt-get install -y libnss-db libdb-dev libcurl4-gnutls-dev libgnutls28-dev libldap2-dev libsasl2-dev
      ### CI-only deps, not in requirements.txt
      #- restore_cache:
      #    keys:
      #    - pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      #    - pip-packages-v1-{{ .Branch }}-
      #    - pip-packages-v1-
      #- run: python -m pip install --user -r requirements.txt
      #- run: python -m pip install --user python-coveralls yapf pylint
      #- save_cache:
      #    key: pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      #    paths:
      #      - /usr/local/bin
      #      - ~/.local/share/virtualenvs/venv
      #- run: export PATH=$PATH:$(python -m site --user-base)/bin
      #- run: python setup.py test --addopts "-v --durations=0 --junitxml=test-results/junit.xml --cov=nss_cache --cov-report term-missing --cov-report html"
      ###- run:
      ###    command: coveralls
      ###    when: always
      #- store_test_results:
      #    path: test-results
      #- store_artifacts:
      #    path: test-results
      #    destination: tr1
      #- store_artifacts:
      #    path: htmlcov
      #- run: sudo python -m pip install .
      #- run: sudo apt install -y slapd ldap-utils libnss-db db-util
      #- run: debian/tests/regtest
      #- run: sudo tests/samba.sh

workflows:
  version: 2
  build:
    jobs:
      - build
