version: 2

jobs:
  build:
    working_directory: ~/nsscache
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0
      - run:
          name: install/update pip pipenv
          command: |
            sudo python -m pip install --upgrade pip setuptools wheel
            #sudo python -m pip install pipenv
      # Install C libraries before pip install.
      - run: sudo apt-get -qq update
      - run: sudo apt-get install -y libnss-db libdb-dev libcurl4-gnutls-dev libgnutls28-dev libldap2-dev libsasl2-dev
      ## CI-only deps, not in requirements.txt
      - restore_cache:
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            #- pip-packages-v1-{{ .Branch }}-
            #- pip-packages-v1-
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --user -r requirements.txt
      - save_cache:
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local/share/virtualenvs/venv
      - run: export PATH=$PATH:$(python3 -m site --user-base)/bin
      - run: python3 setup.py test --addopts "-v --durations=0 --junitxml=test-results/junit.xml --cov=nss_cache --cov-report term-missing --cov-report html"
      ##- run:
      ##    command: coveralls
      ##    when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - store_artifacts:
          path: htmlcov
      - run: sudo -E -H $(which pip) install .
      - run: sudo apt install -y slapd ldap-utils libnss-db db-util
      - run: sudo debian/tests/regtest
      - run: sudo tests/samba.sh
      - run: sudo $(which python3) $(which nsscache) -c tests/nsscache.conf --debug verify
      - run: sudo $(which python3) $(which nsscache) -c tests/nsscache.conf --debug update --full

workflows:
  version: 2
  build:
    jobs:
      - build
