version: 2.1
orbs:
  python: circleci/python@0.2.1
jobs:
  build:
    executor:
      name: "python/default"
      tag: "3.7"
    #working_directory: ~/nsscache
    # docker:
    #   - image: circleci/python:3.7
    #     environment:
    #       PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      # Install C libraries before pip install.
      - run: sudo apt-get install -y libnss-db libdb-dev libcurl4-gnutls-dev libgnutls28-dev libldap2-dev libsasl2-dev
      - python/load-cache
      - python/install-deps
      - python/save-cache
      
      # - run: sudo chown -R circleci:circleci /usr/local/bin
      # - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      # - restore_cache:
      # # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
      #     key: deps9-{{ .Branch }}-{{ checksum "requirements.txt" }}
      # - run:
      #     command: |
      #       sudo pip install pipenv
      #       pipenv install
      # - save_cache: # cache Python dependencies using checksum of Pipfile as the cache-key
      #     key: deps9-{{ .Branch }}-{{ checksum "requirements-txt" }}
      #     paths:
      #       - ".venv"
      #       - "/usr/local/bin"
      #       - "/usr/local/lib/python3.7/site-packages"
      - run: python setup.py test --addopts "--junitxml=test-results/junit.xml --cov-report term-missing --cov nss_cache"
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
