version: 2
jobs:
  build:
    branches:
      only:
        - CircleCi
    docker:
      - image: circleci/python:3.7-buster
      - image: circleci/python:3.8-buster
    #machine:
    #  image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get update -qq
            sudo apt-get install -y libnss-db libdb-dev libcurl4-gnutls-dev libgnutls28-dev libldap2-dev libsasl2-dev
            pip install . --user
            pip install -r requirements.txt --user
            pip install yapf --user
      - run:
          name: Running tests
          command: |
            sudo bash tests/samba.sh
            python3 runtests.py -vvv
            python3 setup.py install --root=/tmp/nsscache
            #yapf --diff --recursive . | tee /dev/tty | wc -l | xargs test 0 -eq || echo "Please format your code (with `yapf`)"
