version: 2.1

jobs:
  build:
    working_directory: ~/nsscache
    docker:
      - image: python/3.8.0-buster
    steps:
      - checkout
      - run: apt-get update && apt-get -y install sudo
      - run: sudo apt-get install -y libnss-db libdb-dev libcurl4-gnutls-dev libgnutls28-dev libldap2-dev libsasl2-dev
      - run: sudo pip install pipenv
      - run: pipenv install
      - run: pipenv run python runtests.py -vvv
      - run: sudo tests/samba.sh
      - run: sudo $(which python3) $(which nsscache) -c tests/nsscache.conf --debug verify
      - run: sudo $(which python3) $(which nsscache) -c tests/nsscache.conf --debug update --full

workflows:
  version: 2
  build:
    jobs:
      - build
