version: 2

jobs:
  build:
    working_directory: ~/nsscache
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0
      # Install C libraries before pip install.
      - run: sudo apt-get -qq update
      - run: sudo apt-get install -y libnss-db libdb-dev libcurl4-gnutls-dev libgnutls28-dev libldap2-dev libsasl2-dev
      #- run: sudo pip install pipenv
      #- run: pipenv install
      ## CI-only deps, not in requirements.txt
      - restore_cache:
          #key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          - pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          - pip-packages-v1-{{ .Branch }}-
          - pip-packages-v1-
      - run:
          command: |
            sudo pip install pipenv
            pipenv install
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      #- run: sudo chown -R circleci:circleci /usr/local/bin
      #- run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - save_cache:
          #key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
          paths:
            - ~/.local/share/virtualenvs/venv
            #- ".venv"
            #- "/usr/local/bin"
            #- "/usr/local/lib/python3.7/site-packages"
      - run: export PATH=$PATH:$(python -m site --user-base)/bin
      - run: pipenv run python setup.py test --addopts "-v --durations=0 --junitxml=test-results/junit.xml --cov=nss_cache --cov-report term-missing --cov-report html"
      ##- run:
      ##    command: coveralls
      ##    when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - store_artifacts:
          path: htmlcov
      - run: pip install --user .
      - run: sudo apt install -y slapd ldap-utils libnss-db db-util
      - run: debian/tests/regtest
      - run: sudo tests/samba.sh

workflows:
  version: 2
  build:
    jobs:
      - build
