version: 2

jobs:
  build:
    working_directory: ~/nsscache
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Make PATH available globally
          command: |
            echo 'export PATH=$PATH:/home/circleci/.local/bin' >> $BASH_ENV
      - run:
          name: "Set Python Version"
          command: pyenv global 3.7.0
      # Install C libraries before pip install.
      - run: sudo apt-get -qq update
      - run: sudo apt-get install -y libnss-db libdb-dev libcurl4-gnutls-dev libgnutls28-dev libldap2-dev libsasl2-dev
      - restore_cache:
          keys:
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install --upgrade pip pipenv &&  pip3 install --upgrade pip pipenv
            pipenv install
            pipenv install python-coveralls yapf pylint
      - save_cache:
          key: pip-packages-v1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/opt/circleci/.pyenv/versions/3.7.0/lib/python3.7/site-packages"
      - run: 
          command: |
            pipenv run python setup.py test --addopts "-v --durations=0 --junitxml=test-results/junit.xml --cov=nss_cache --cov-report term-missing --cov-report html"
      ##- run:
      ##    command: coveralls
      ##    when: always
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - store_artifacts:
          path: htmlcov
      - run: 
          command: |
            pipenv install .
            sudo apt install -y slapd ldap-utils libnss-db db-util
            #pipenv run debian/tests/regtest
            sudo tests/samba.sh
      - run:
          command: | 
            pipenv run yapf --diff --recursive nss_cache nsscache
          no_output_timeout: 20m
      - run:
          command: |
            pipenv run pylint nsscache nss_cache || true

workflows:
  version: 2
  build:
    jobs:
      - build
