version: 2.0
jobs:
  build:
    working_directory: ~/nsscache
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run: sudo apt-get install -y libnss-db libdb-dev libcurl4-gnutls-dev libgnutls28-dev libldap2-dev libsasl2-dev
      - run: sudo pip install pipenv
      - run: pipenv install
      - run: pipenv run python runtests.py -vvv
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
