version: 2.1
orbs:
  python: circleci/python@0.2.1
jobs:
  build:
    executor:
      name: "python/default"
      tag: "3.7"
    steps:
      - checkout
      # Install C libraries before pip install.
      - run: sudo apt-get install -y libnss-db libdb-dev libcurl4-gnutls-dev libgnutls28-dev libldap2-dev libsasl2-dev
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run: pip install --user python-coveralls
      - run: python setup.py test --addopts "-v --durations=0 --junitxml=test-results/junit.xml --cov=nss_cache --cov-report term-missing --cov-report html"
      - run: $(python -m site --user-base)/bin/coveralls
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
          destination: tr1
      - store_artifacts:
          path: htmlcov
